### ISSUE TITLE
Can't find ProcessGroupNCCL.hpp

### ISSUE THREAD

**Issue by zjujh1995** [laekov/fastmoe#16]
Hi all. I've installed fmoe without USE_NCCL option successfully. However, when I turned on this option, I got the following error: 

cuda/moe.cpp:112:37: fatal error: c10d/ProcessGroupNCCL.hpp: No such file or directory.

Environment：
PyTorch 1.3，Cuda 10.0， Linux

Looking foward to your advice.

**Comment by laekov** [comment]
This issue seems to happen because your PyTorch is too old to correctly provide that header file to FastMoE's cpp extensions.

I strongly recommend you to upgrade your PyTorch to the newest release, v1.8.0, and see if this issue is addressed.

You may also disable FastMoE's feature of distributed experts by setting environment variable `USE_NCCL=0` when running `setup.py`.

**Comment by zjujh1995** [comment]
Many thanks for your fast reply. But PyTorch version is fixed on the computation platform that I'm using. I'll try to manually add some missing head files and see if it will work.

**Comment by zjujh1995** [comment]
Hi, I figure out a method to update my PyTorch, but there's still a problem when installing fmoe, as following:

cuda/moe_comm_kernel.cu(24): error: identifier "ncclSend" is undefined

I've checked the nccl version by calling `torch.cuda.nccl.version()`, and it returned 2408 which seems to be normal.

**Comment by laekov** [comment]
> Hi, I figure out a method to update my PyTorch, but there's still a problem when installing fmoe, as following:
> 
> `cuda/moe_comm_kernel.cu(24): error: identifier "ncclSend" is undefined`
> 
> I've checked the nccl version by calling `torch.cuda.nccl.version()`, and it returned 2408 which seems to be normal.

You are supposed to use NCCL 2708 or later, as mentioned in our readme. Ncclsend is not provided by nccl until 2708.

**Comment by BinHeRunning** [comment]
Hi, an error occurs when i install with USE_NCCL=1:

RuntimeErrorRuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:825, unhandled system error, NCCL version 2.7.8
ncclSystemError: System call (socket, malloc, munmap, etc) failed.

Env:
1. torch 1.8
2. cuda 10.2
3. nccl 2.7.8

Has anyone had a similar problem ?

**Comment by Xiang-Pan** [comment]
Python 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.nccl.version()
(2, 14, 3)
>>> torch.__version__
'1.13.0+cu117'

Still an error with 1.13

**Comment by ScottHoang** [comment]
Hi, I also have an identical error with 
torch v 1.13.0
nccl   v 2.14.3

**Comment by laekov** [comment]
> Hi, I also have an identical error with torch v 1.13.0 nccl v 2.14.3

Yes, PyTorch again changes its include path for cuda extensions in v1.13.0. We need a new fix.

**Comment by laekov** [comment]
Fixed in #142 @ScottHoang @Xiang-Pan
